pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/dev-patel05/ci-cd.git'
            }
        }

        stage('Validate Files') {
            steps {
                echo "Listing project files..."
                sh 'ls -l'
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: '**/*', fingerprint: true
            }
        }

        stage('Deploy to EC2 Web Server') {
            steps {
                sshagent(credentials: ['ec2-ssh-key']) {
                    sh '''
                        echo "🚀 Starting Deployment..."

                        # Check 'public' folder exists
                        if [ ! -d "public" ]; then
                            echo "❌ ERROR: public/ folder does not exist!"
                            exit 1
                        fi

                        # Preparing EC2 folder
                        ssh -o StrictHostKeyChecking=no ubuntu@54.234.145.116 "sudo mkdir -p /var/www/html && sudo chown ubuntu:ubuntu /var/www/html"

                        # Clean old files
                        ssh -o StrictHostKeyChecking=no ubuntu@54.234.145.116 "rm -rf /var/www/html/*"

                        # Upload new build files
                        scp -o StrictHostKeyChecking=no -r public/* ubuntu@54.234.145.116:/var/www/html/

                        echo "✅ Deployment Completed Successfully!"
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "🎉 Deployment Success!"
        }
        failure {
            echo "❌ Deployment Failed!"
        }
    }
}
